#currently only used for our development environment

version: '2'
services:
  migration:
    build: .
    command: '/bin/bash -l -c "bundle install; rake db:create"'
    volumes:
      - .:/app
    volumes_from:
      - container:ruby_gems
    depends_on:
      - db
    environment:
      RAILS_ENV: development
  web:
    depends_on:
      - migration
    build: .
    command: '/bin/bash -l -c "bundle install; rm tmp/pids/server.pid; foreman start -f Procfile.hot"'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    volumes_from:
      - container:ruby_gems
    environment:
      SPHINX_HOST: search
      BUTTER_TOKEN: 03cad913262d44335d34f1c28e011a45126c2790
      AWS_ACCESS_KEY_ID: AKIAJIZ5VYU4FPBOTWLQ
      AWS_SECRET_ACCESS_KEY: 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
      S3_BUCKET_NAME: assets.tackhunter-dev.com
    ports:
      - "3000:3000"
      - "9001:9001"
  worker:
    depends_on:
      - migration
    build: .
    command: '/bin/bash -l -c "bundle install; bundle exec rake jobs:work"'
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    volumes_from:
      - container:ruby_gems
    environment:
      SPHINX_HOST: search
      BUTTER_TOKEN: 03cad913262d44335d34f1c28e011a45126c2790
      AWS_ACCESS_KEY_ID: AKIAJIZ5VYU4FPBOTWLQ
      AWS_SECRET_ACCESS_KEY: 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
      S3_BUCKET_NAME: assets.tackhunter-dev.com
  db:
    image: mysql
    volumes_from:
      - container:mysqldata
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  search:
    build: .
    command: '/bin/bash -l -c "bundle exec rake ts:configure ts:index; searchd --nodetach --pidfile --config config/development.sphinx.conf"'
    depends_on: 
      - migration
    volumes:
      - .:/app
    volumes_from:
      - container:ruby_gems
    ports:
      - "3563:3563"
    environment:
      SPHINX_HOST: ""
